namespace EnvDTE
{
    public enum vsWindowType
    {
        vsWindowTypeCodeWindow,
        vsWindowTypeDesigner,
        vsWindowTypeBrowser,
        vsWindowTypeWatch,
        vsWindowTypeLocals,
        vsWindowTypeImmediate,
        vsWindowTypeSolutionExplorer,
        vsWindowTypeProperties,
        vsWindowTypeFind,
        vsWindowTypeFindReplace,
        vsWindowTypeToolbox,
        vsWindowTypeLinkedWindowFrame,
        vsWindowTypeMainWindow,
        vsWindowTypePreview,
        vsWindowTypeColorPalette,
        vsWindowTypeToolWindow,
        vsWindowTypeDocument,
        vsWindowTypeOutput,
        vsWindowTypeTaskList,
        vsWindowTypeAutos,
        vsWindowTypeCallStack,
        vsWindowTypeThreads,
        vsWindowTypeDocumentOutline,
        vsWindowTypeRunningDocuments
    }
}
