namespace Microsoft.VisualStudio.Shell.Interop
{
    public enum __BUILDOUTOFDATEPROJECTS
    {
        BUILDOUTOFDATEPROJECTS_YES = 0,
        BUILDOUTOFDATEPROJECTS_NO = 1,
        BUILDOUTOFDATEPROJECTS_MAX = 2,
        BUILDOUTOFDATEPROJECTS_PROMPT = 2
    }
}
