namespace Microsoft.VisualStudio.Shell.Interop
{
    public enum __VSSYSCOLOREX
    {

    VSCOLOR_LASTEX = -178,

    VSCOLOR_WIZARD_ORIENTATIONPANEL_TEXT = -178,

    VSCOLOR_WIZARD_ORIENTATIONPANEL_BACKGROUND = -177,

    VSCOLOR_TOOLWINDOW_TAB_SELECTEDTEXT = -176,

    VSCOLOR_TOOLWINDOW_TAB_TEXT = -175,

    VSCOLOR_TOOLWINDOW_TAB_GRADIENTEND = -174,

    VSCOLOR_TOOLWINDOW_TAB_GRADIENTBEGIN = -173,

    VSCOLOR_TOOLWINDOW_TAB_BORDER = -172,

    VSCOLOR_TOOLWINDOW_TAB_SELECTEDTAB = -171,

    VSCOLOR_TOOLWINDOW_TEXT = -170,

    VSCOLOR_TOOLWINDOW_BUTTON_HOVER_INACTIVE_BORDER = -169,

    VSCOLOR_TOOLWINDOW_BUTTON_HOVER_INACTIVE = -168,

    VSCOLOR_TOOLWINDOW_BUTTON_HOVER_ACTIVE_BORDER = -167,

    VSCOLOR_TOOLWINDOW_BUTTON_HOVER_ACTIVE = -166,

    VSCOLOR_TOOLWINDOW_BUTTON_DOWN_BORDER = -165,

    VSCOLOR_TOOLWINDOW_BUTTON_DOWN = -164,

    VSCOLOR_TOOLWINDOW_BORDER = -163,

    VSCOLOR_TOOLWINDOW_BACKGROUND = -162,

    VSCOLOR_TOOLBOX_ICON_SHADOW = -161,

    VSCOLOR_TOOLBOX_ICON_HIGHLIGHT = -160,

    VSCOLOR_TOOLBOX_HEADINGEND = -159,

    VSCOLOR_TOOLBOX_HEADINGBEGIN = -158,

    VSCOLOR_TOOLBOX_HEADINGACCENT = -157,

    VSCOLOR_TOOLBOX_GRADIENTLIGHT = -156,

    VSCOLOR_TOOLBOX_GRADIENTDARK = -155,

    VSCOLOR_TOOLBOX_DIVIDER = -154,

    VSCOLOR_TOOLBOX_BACKGROUND = -153,

    VSCOLOR_TITLEBAR_INACTIVE_TEXT = -152,

    VSCOLOR_TITLEBAR_INACTIVE_GRADIENTEND = -151,

    VSCOLOR_TITLEBAR_INACTIVE_GRADIENTBEGIN = -150,

    VSCOLOR_TITLEBAR_INACTIVE = -149,

    VSCOLOR_TITLEBAR_ACTIVE_TEXT = -148,

    VSCOLOR_TITLEBAR_ACTIVE_GRADIENTEND = -147,

    VSCOLOR_TITLEBAR_ACTIVE_GRADIENTBEGIN = -146,

    VSCOLOR_TITLEBAR_ACTIVE = -145,

    VSCOLOR_TASKLIST_GRIDLINES = -144,

    VSCOLOR_SORT_TEXT = -143,

    VSCOLOR_SORT_BACKGROUND = -142,

    VSCOLOR_SNAPLINES_TEXTBASELINE = -141,

    VSCOLOR_SNAPLINES_PADDING = -140,

    VSCOLOR_SNAPLINES = -139,

    VSCOLOR_SMARTTAG_TEXT = -138,

    VSCOLOR_SMARTTAG_HOVER_TEXT = -137,

    VSCOLOR_SMARTTAG_HOVER_FILL = -136,

    VSCOLOR_SMARTTAG_HOVER_BORDER = -135,

    VSCOLOR_SMARTTAG_FILL = -134,

    VSCOLOR_SMARTTAG_BORDER = -133,

    VSCOLOR_SIDEBAR_TEXT = -132,

    VSCOLOR_SIDEBAR_GRADIENTLIGHT = -131,

    VSCOLOR_SIDEBAR_GRADIENTDARK = -130,

    VSCOLOR_SIDEBAR_BACKGROUND = -129,

    VSCOLOR_SCREENTIP_TEXT = -128,

    VSCOLOR_SCREENTIP_BACKGROUND = -127,

    VSCOLOR_SCREENTIP_BORDER = -126,

    VSCOLOR_PROJECTDESIGNER_TAB_SEP_TOP_GRADIENTEND = -125,

    VSCOLOR_PROJECTDESIGNER_TAB_SEP_TOP_GRADIENTBEGIN = -124,

    VSCOLOR_PROJECTDESIGNER_TAB_SEP_BOTTOM_GRADIENTEND = -123,

    VSCOLOR_PROJECTDESIGNER_TAB_SEP_BOTTOM_GRADIENTBEGIN = -122,

    VSCOLOR_PROJECTDESIGNER_TAB_SELECTED_BACKGROUND = -121,

    VSCOLOR_PROJECTDESIGNER_TAB_SELECTED_HIGHLIGHT2 = -120,

    VSCOLOR_PROJECTDESIGNER_TAB_SELECTED_HIGHLIGHT1 = -119,

    VSCOLOR_PROJECTDESIGNER_TAB_SELECTED_BORDER = -118,

    VSCOLOR_PROJECTDESIGNER_TAB_SELECTED_INSIDEBORDER = -117,

    VSCOLOR_PROJECTDESIGNER_TAB_BACKGROUND_GRADIENTEND = -116,

    VSCOLOR_PROJECTDESIGNER_TAB_BACKGROUND_GRADIENTBEGIN = -115,

    VSCOLOR_PROJECTDESIGNER_CONTENTS_BACKGROUND = -114,

    VSCOLOR_PROJECTDESIGNER_BORDER_INSIDE = -113,

    VSCOLOR_PROJECTDESIGNER_BORDER_OUTSIDE = -112,

    VSCOLOR_PROJECTDESIGNER_BACKGROUND_GRADIENTEND = -111,

    VSCOLOR_PROJECTDESIGNER_BACKGROUND_GRADIENTBEGIN = -110,

    VSCOLOR_PANEL_TITLEBAR_UNSELECTED = -109,

    VSCOLOR_PANEL_TITLEBAR_TEXT = -108,

    VSCOLOR_PANEL_TITLEBAR = -107,

    VSCOLOR_PANEL_TEXT = -106,

    VSCOLOR_PANEL_SUBGROUPSEPARATOR = -105,

    VSCOLOR_PANEL_SEPARATOR = -104,

    VSCOLOR_PANEL_HYPERLINK_PRESSED = -103,

    VSCOLOR_PANEL_HYPERLINK_HOVER = -102,

    VSCOLOR_PANEL_HYPERLINK = -101,

    VSCOLOR_PANEL_HOVEROVERCLOSE_FILL = -100,

    VSCOLOR_PANEL_HOVEROVERCLOSE_BORDER = -99,

    VSCOLOR_PANEL_GRADIENTLIGHT = -98,

    VSCOLOR_PANEL_GRADIENTDARK = -97,

    VSCOLOR_PANEL_BORDER = -96,

    VSCOLOR_MDICLIENT_BORDER = -95,

    VSCOLOR_HELP_SEARCH_PANEL_RULES = -94,

    VSCOLOR_HELP_SEARCH_TEXT = -93,

    VSCOLOR_HELP_SEARCH_BACKGROUND = -92,

    VSCOLOR_HELP_SEARCH_RESULT_SELECTED_TEXT = -91,

    VSCOLOR_HELP_SEARCH_RESULT_SELECTED_BACKGROUND = -90,

    VSCOLOR_HELP_SEARCH_RESULT_LINK_UNSELECTED = -89,

    VSCOLOR_HELP_SEARCH_RESULT_LINK_SELECTED = -88,

    VSCOLOR_HELP_SEARCH_PROVIDER_ICON = -87,

    VSCOLOR_HELP_SEARCH_PROVIDER_SELECTED_TEXT = -86,

    VSCOLOR_HELP_SEARCH_PROVIDER_SELECTED_BACKGROUND = -85,

    VSCOLOR_HELP_SEARCH_PROVIDER_UNSELECTED_TEXT = -84,

    VSCOLOR_HELP_SEARCH_PROVIDER_UNSELECTED_BACKGROUND = -83,

    VSCOLOR_HELP_SEARCH_FITLER_BORDER = -82,

    VSCOLOR_HELP_SEARCH_FITLER_BACKGROUND = -81,

    VSCOLOR_HELP_SEARCH_FITLER_TEXT = -80,

    VSCOLOR_HELP_SEARCH_BORDER = -79,

    VSCOLOR_HELP_SEARCH_FRAME_TEXT = -78,

    VSCOLOR_HELP_SEARCH_FRAME_BACKGROUND = -77,

    VSCOLOR_HELP_HOWDOI_TASK_TEXT = -76,

    VSCOLOR_HELP_HOWDOI_TASK_LINK = -75,

    VSCOLOR_HELP_HOWDOI_TASK_BACKGROUND = -74,

    VSCOLOR_HELP_HOWDOI_PANE_TEXT = -73,

    VSCOLOR_HELP_HOWDOI_PANE_LINK = -72,

    VSCOLOR_HELP_HOWDOI_PANE_BACKGROUND = -71,

    VSCOLOR_GRID_LINE = -70,

    VSCOLOR_GRID_HEADING_TEXT = -69,

    VSCOLOR_GRID_HEADING_BACKGROUND = -68,

    VSCOLOR_FORMSMARTTAG_OBJECTTAG_FILL = -67,

    VSCOLOR_FORMSMARTTAG_OBJECTTAG_BORDER = -66,

    VSCOLOR_FORMSMARTTAG_ACTIONTAG_FILL = -65,

    VSCOLOR_FORMSMARTTAG_ACTIONTAG_BORDER = -64,

    VSCOLOR_FILETAB_TEXT = -63,

    VSCOLOR_FILETAB_SELECTEDTEXT = -62,

    VSCOLOR_FILETAB_SELECTEDBORDER = -61,

    VSCOLOR_FILETAB_SELECTEDBACKGROUND = -60,

    VSCOLOR_FILETAB_GRADIENTLIGHT = -59,

    VSCOLOR_FILETAB_GRADIENTDARK = -58,

    VSCOLOR_FILETAB_CHANNELBACKGROUND = -57,

    VSCOLOR_FILETAB_BORDER = -56,

    VSCOLOR_ENVIRONMENT_BACKGROUND_GRADIENTEND = -55,

    VSCOLOR_ENVIRONMENT_BACKGROUND_GRADIENTBEGIN = -54,

    VSCOLOR_ENVIRONMENT_BACKGROUND = -53,

    VSCOLOR_EDITOR_EXPANSION_TEXT = -52,

    VSCOLOR_EDITOR_EXPANSION_LINK = -51,

    VSCOLOR_EDITOR_EXPANSION_FILL = -50,

    VSCOLOR_EDITOR_EXPANSION_BORDER = -49,

    VSCOLOR_DESIGNER_WATERMARK = -48,

    VSCOLOR_DESIGNER_TRAY = -47,

    VSCOLOR_DESIGNER_SELECTIONDOTS = -46,

    VSCOLOR_DESIGNER_BACKGROUND = -45,

    VSCOLOR_DEBUGGER_DATATIP_INACTIVE_TEXT = -44,

    VSCOLOR_DEBUGGER_DATATIP_INACTIVE_SEPARATOR = -43,

    VSCOLOR_DEBUGGER_DATATIP_INACTIVE_HIGHLIGHTTEXT = -42,

    VSCOLOR_DEBUGGER_DATATIP_INACTIVE_HIGHLIGHT = -41,

    VSCOLOR_DEBUGGER_DATATIP_INACTIVE_BORDER = -40,

    VSCOLOR_DEBUGGER_DATATIP_INACTIVE_BACKGROUND = -39,

    VSCOLOR_DEBUGGER_DATATIP_ACTIVE_TEXT = -38,

    VSCOLOR_DEBUGGER_DATATIP_ACTIVE_SEPARATOR = -37,

    VSCOLOR_DEBUGGER_DATATIP_ACTIVE_HIGHLIGHTTEXT = -36,

    VSCOLOR_DEBUGGER_DATATIP_ACTIVE_HIGHLIGHT = -35,

    VSCOLOR_DEBUGGER_DATATIP_ACTIVE_BORDER = -34,

    VSCOLOR_DEBUGGER_DATATIP_ACTIVE_BACKGROUND = -33,

    VSCOLOR_CONTROL_OUTLINE = -32,

    VSCOLOR_CONTROL_LINK_TEXT_PRESSED = -31,

    VSCOLOR_CONTROL_LINK_TEXT_HOVER = -30,

    VSCOLOR_CONTROL_LINK_TEXT = -29,

    VSCOLOR_CONTROL_EDIT_REQUIRED_HINTTEXT = -28,

    VSCOLOR_CONTROL_EDIT_REQUIRED_BACKGROUND = -27,

    VSCOLOR_CONTROL_EDIT_HINTTEXT = -26,

    VSCOLOR_COMMANDBAR_TEXT_SELECTED = -25,

    VSCOLOR_COMMANDBAR_TEXT_INACTIVE = -24,

    VSCOLOR_COMMANDBAR_TEXT_HOVER = -23,

    VSCOLOR_COMMANDBAR_TEXT_ACTIVE = -22,

    VSCOLOR_COMMANDBAR_SHADOW = -21,

    VSCOLOR_COMMANDBAR_SELECTED = -20,

    VSCOLOR_COMMANDBAR_HOVEROVERSELECTEDICON_BORDER = -19,

    VSCOLOR_COMMANDBAR_HOVEROVERSELECTEDICON = -18,

    VSCOLOR_COMMANDBAR_HOVEROVERSELECTED = -17,

    VSCOLOR_COMMANDBAR_HOVER = -16,

    VSCOLOR_COMMANDBAR_GRADIENT_MIDDLE = -15,

    VSCOLOR_COMMANDBAR_GRADIENT_END = -14,

    VSCOLOR_COMMANDBAR_GRADIENT_BEGIN = -13,

    VSCOLOR_COMMANDBAR_DRAGHANDLE_SHADOW = -12,

    VSCOLOR_COMMANDBAR_DRAGHANDLE = -11,

    VSCOLOR_COMMANDBAR_BORDER = -10,

    VSCOLOR_ACCENT_PALE = -9,

    VSCOLOR_ACCENT_MEDIUM = -8,

    VSCOLOR_ACCENT_LIGHT = -7,

    VSCOLOR_ACCENT_DARK = -6,

    VSCOLOR_ACCENT_BORDER = -5,
    }
}
