namespace Microsoft.VisualStudio.Shell.Interop
{
    public enum __VSCURSORTYPE
    {

    VSCURSOR_APPSTARTING = 1,

    VSCURSOR_COLUMNSPLIT_EW = 2,

    VSCURSOR_COLUMNSPLIT_NS = 3,

    VSCURSOR_CONTROL_COPY = 4,

    VSCURSOR_CONTROL_DELETE = 5,

    VSCURSOR_CONTROL_MOVE = 6,

    VSCURSOR_CROSS = 7,

    VSCURSOR_DRAGDOCUMENT_MOVE = 8,

    VSCURSOR_DRAGDOCUMENT_NOEFFECT = 9,

    VSCURSOR_DRAGSCRAP_COPY = 10,

    VSCURSOR_DRAGSCRAP_MOVE = 11,

    VSCURSOR_DRAGSCRAP_SCROLL = 12,

    VSCURSOR_HAND = 13,

    VSCURSOR_IBEAM = 14,

    VSCURSOR_ISEARCH = 15,

    VSCURSOR_ISEARCH_UP = 16,

    VSCURSOR_MACRO_RECORD_NO = 17,

    VSCURSOR_NO = 18,

    VSCURSOR_NOMOVE_2D = 19,

    VSCURSOR_NOMOVE_HORIZ = 20,

    VSCURSOR_NOMOVE_VERT = 21,

    VSCURSOR_PAN_EAST = 22,

    VSCURSOR_PAN_NE = 23,

    VSCURSOR_PAN_NORTH = 24,

    VSCURSOR_PAN_NW = 25,

    VSCURSOR_PAN_SE = 26,

    VSCURSOR_PAN_SOUTH = 27,

    VSCURSOR_PAN_SW = 28,

    VSCURSOR_PAN_WEST = 29,

    VSCURSOR_POINTER = 30,

    VSCURSOR_POINTER_REVERSE = 31,

    VSCURSOR_SIZE_NS = 32,

    VSCURSOR_SIZE_EW = 33,

    VSCURSOR_SIZE_NWSE = 34,

    VSCURSOR_SIZE_NESW = 35,

    VSCURSOR_SIZE_ALL = 36,

    VSCURSOR_SPLIT_EW = 37,

    VSCURSOR_SPLIT_NS = 38,

    VSCURSOR_UPARROW = 39,

    VSCURSOR_WAIT = 40,
    }
}
