namespace Microsoft.VisualStudio.Shell.Interop
{
    public enum _LIB_FLAGS2
    {

        LF_SUPPORTSPROJECTREFERENCES = 16,

        LF_SUPPORTSFILTERING = 32,

        LF_SUPPORTSFILTERINGWITHEXPANSION = 64,

        LF_SUPPORTSCALLBROWSER = 128,

        LF_SUPPORTSLISTREFERENCES = 256,

        LF_SUPPORTSALWAYSUPDATE = 1024,

        LF_SUPPORTSBASETYPES = 2048,

        LF_SUPPORTSDERIVEDTYPES = 4096,

        LF_SUPPORTSINHERITEDMEMBERS = 8192,

        LF_SUPPORTSPRIVATEMEMBERS = 16384,

        LF_SUPPORTSCLASSDESIGNER = 32768,

        LF_SHOWFULLNAMESINFINDSYMBOLRESULTS = 65536,
    }
}
