namespace Microsoft.VisualStudio.Shell.Interop
{
    public enum _VSOBJLISTELEMPROPID
    {

        VSOBJLISTELEMPROPID_FIRST = 1,

        VSOBJLISTELEMPROPID_HELPKEYWORD = 1,

        VSOBJLISTELEMPROPID_COMPONENTPATH = 2,

        VSOBJLISTELEMPROPID_CODEDEFVIEWCONTEXT = 3,

        VSOBJLISTELEMPROPID_SUPPORTSCALLSTO = 4,

        VSOBJLISTELEMPROPID_SUPPORTSCALLSFROM = 5,

        VSOBJLISTELEMPROPID_FULLNAME = 6,

        VSOBJLISTELEMPROPID_LEAFNAME = 7,

        VSOBJLISTELEMPROPID_LAST = 8,

        VSOBJLISTELEMPROPID_NAME_FOR_RENAME = 8,
    }
}
